name: Generate Matrix of Magento Versions
description: Generates single database version per Magento release for both MariaDB and MySQL
author: Ivan Chepurnyi <ivan@ecom.dev>
inputs:
  version:
    required: false
    description: Specify version of magento to build instead of all versions
  variation:
    required: false
    description: Specify variation of magento to build instead of all variation
outputs:
  magento:
    description: JSON with versions of Magento to build with all variations
  containers:
    description: JSON with container build specification based on Magento artifacts
runs:
  using: node20
  main: dist/index.js
