name: Build Docker Image Based on Provided Data Artifact
description: Generates single database version per Magento release for both MariaDB and MySQL
author: Ivan Chepurnyi <ivan@ecom.dev>
inputs:
  artifact:
    required: true
    description: Name of artifact to build image from
  containerType:
    description: Container Type
    required: true
  registry:
    description: Container registry
    default: ghcr.io
  username:
    description: Container registry username
  password:
    description: Container registry password
  imageName:
    description: Image name
    required: true
  imageTags:
    description: Image Tags
    required: true
  push:
    default: 'false'
    description: Push Images to repository
  version:
    required: true
    description: Base version of image to use
  platforms:
    required: false
    description: Platforms Docker Image build
    default: linux/amd64,linux/arm64
runs:
  using: composite
  steps:
    - name: Create artifact directory
      run: mkdir -p artifact/
      shell: bash

    - name: Download artifact
      uses: actions/download-artifact@v7
      with:
        github-token: ${{ inputs.password }}
        path: artifact/
        name: ${{ inputs.artifact }}

    - name: Unpack search directory
      run: |
        cd artifact
        # Unpack search index data
        tar xzvf search.tgz
        # Remove lock files from search instance
        find ./search -type f -name '*.lock' | xargs rm
      shell: bash

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ inputs.registry }}
      if: inputs.push != 'false'
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.imageName }}
        tags: ${{ inputs.imageTags }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        context: artifact/
        file: ${{ github.action_path  }}/Dockerfile-${{ inputs.containerType }}
        push: ${{ inputs.push != 'false' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: SOURCE_VERSION=${{ inputs.version }}
    - name: Generate artifact attestation
      if: ${{ inputs.push != 'false' }}
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: ${{ inputs.registry }}/${{ inputs.imageName }}
        subject-digest: ${{ steps.build-and-push.outputs.digest }}
        push-to-registry: ${{ inputs.push != 'false' }}
