name: PHP Package
on:
  push:
    paths:
      - testcontainers-magento-data-php/**
      - composer.json
      - .github/workflows/php-*
  pull_request:
    paths:
      - testcontainers-magento-data-php/**
      - composer.json
      - .github/workflows/php-*
jobs:
  format-check:
    name: Check PSR12 Standarts
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
      - run: composer install
        shell: bash
      - run: composer test
        shell: bash
  tests:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
      - run: composer install
        shell: bash
      - run: composer test
        shell: bash
